### PR TITLE
Additional calls

### PR DESCRIPTION
**Pull request by joshuadwire**
Add support for app fees, refunds, voiding charges, and callback_uris

### CODE REVIEW

**Comment by joshuadwire** [comment]
The omnipay/common v2.4 seems to conflict with other omnipay drivers and omnipay core that only require v2.3

**Comment by w3guy** [comment]
Could you let me know of the conflicts with omnipay 2.4 with other drivers? Detail explanation with screenshots where possible is welcome.

**Comment by w3guy** [comment]
@joshuadwire also, Include test for the newly added feature.

**Comment by joshuadwire** [comment]
Here's the composer conflict we were getting until I switched to omnipay/common 2.3:
screen shot 2016-05-21 at 10 51 23 am

It's from this Travis build: https://travis-ci.org/invoiceninja/invoiceninja/builds/130928330

**Comment by w3guy** [comment]
Can you show me your project composer.json file so i can try reproduce the error?

**Comment by joshuadwire** [comment]
The project is https://github.com/invoiceninja/invoiceninja.

**Comment by joshuadwire** [comment]
I should have mentioned, I'm developing in this branch of a fork: https://github.com/joshuadwire/invoiceninja/tree/wepay-integration

That's the composer.json you'll probably want to look at, but, since it's pointing to my branch of this repository with the different omnipay version, you won't see the error.

**Comment by joshuadwire** [comment]
I've committed tests.

**Comment by w3guy** [comment]
While we await testing your PR, could you add test for the following methods https://coveralls.io/builds/6276843/source?filename=src%2FGateway.php

**Comment by joshuadwire** [comment]
@collizo4sky I'm not sure I'm testing them correctly, since I didn't add those functions, but I did add tests for them. It looks like Travis didn't run the tests though since I pushed during the Github outage earlier today. Do you have a way to manually run them? I'm not set up to run them locally.

**Comment by w3guy** [comment]
@joshuadwire you've done well. Will find time next week to review this PR.

Thanks.

**Comment by joshuadwire** [comment]
@collizo4sky Any update on this?

**Comment by w3guy** [comment]
@joshuadwire thanks for this. 1.3 released.

**Pull request merged**
